/* Subjects */ 
export const FETCH_SUBJECTS_BEGIN = 'FETCH_SUBJECTS_BEGIN';
export const FETCH_SUBJECTS_SUCCESS = 'FETCH_SUBJECTS_SUCCESS';
export const FETCH_SUBJECTS_FAILURE ='FETCH_SUBJECTS_FAILURE';

/* Chapters */
export const FETCH_CHAPTERS_BEGIN = 'FETCH_CHAPTERS_BEGIN';
export const FETCH_CHAPTERS_SUCCESS = 'FETCH_CHAPTERS_SUCCESS';
export const FETCH_CHAPTERS_FAILURE = 'FETCH_CHAPTERS_FAILURE';
